global:
  scrape_interval: 15s   # How often Prometheus scrapes metrics

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "localhost:9093"

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape Node Exporter on remote server
  - job_name: 'node_1'
    static_configs:
      - targets: ['54.85.61.235:9100']

rule_files:
  - "alert-rules.yml"
