[target_nodes]
3.238.3.187 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/Ansible/newkey.pem

3.227.12.113 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/Ansible/newkey.pem

13.219.244.253 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/Ansible/newkey.pem

34.205.53.196 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/Ansible/newkey.pem

34.201.11.37 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/Ansible/newkey.pem

3.238.34.6 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/Ansible/newkey.pem

3.239.108.235 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/Ansible/newkey.pem

13.222.124.34 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/Ansible/newkey.pem

44.192.131.243 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/Ansible/newkey.pem

13.222.106.225 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/Ansible/newkey.pem
